### ISSUE TITLE
CI/tests failing

### ISSUE THREAD

**Issue by villander** [ember-engines/ember-asset-loader#103]
After run `yarn run test:sauce`

```
Last login: Sun May 10 19:56:15 on ttys001
➜  ember-asset-loader git:(master) yarn run test:sauce
yarn run v1.22.4
$ ember test --config-file testem.sauce.js --test-port 7000
WARNING: Node v12.13.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
DEPRECATION: Ember will stop including jQuery by default in an upcoming version. If you wish keep using jQuery in your application explicitly add `@ember/jquery` to your package.json
Environment: test
Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory, open '/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/broccoli-9719scuSj4FGFmkw/out-123-broccoli_debug_debug_7_vendor_js/vendor/ember/ember.debug.map'
Warning: ignoring input sourcemap for vendor/ember/ember-testing.js because ENOENT: no such file or directory, open '/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/broccoli-9719scuSj4FGFmkw/out-147-broccoli_debug_debug_10_test_support_js/vendor/ember/ember-testing.map'
cleaning up...
Built project successfully. Stored in "/Users/villander/Projects/ember-asset-loader/tmp/class-tests_dist-zfQE2hCj.tmp".
not ok 1 SL_CHROME - [undefined ms] - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Stderr: 
             Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.
                at launch (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/launch.js:21:28)
                at main (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/index.js:7:10)
                at Object.<anonymous> (/Users/villander/Projects/ember-asset-loader/node_modules/ember-cli-sauce/bin/cli.js:6:1)
                at Module._compile (internal/modules/cjs/loader.js:956:30)
                at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
                at Module.load (internal/modules/cjs/loader.js:812:32)
                at Function.Module._load (internal/modules/cjs/loader.js:724:14)
                at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
                at internal/main/run_main_module.js:17:11
            
            Stdout: 
             Bail out! Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.
            
            
        Log: |
            { type: 'error', text: 'Error: Browser exited unexpectedly' }
            {
              type: 'error',
              text: 'Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.\n' +
                '    at launch (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/launch.js:21:28)\n' +
                '    at main (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/index.js:7:10)\n' +
                '    at Object.<anonymous> (/Users/villander/Projects/ember-asset-loader/node_modules/ember-cli-sauce/bin/cli.js:6:1)\n' +
                '    at Module._compile (internal/modules/cjs/loader.js:956:30)\n' +
                '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n' +
                '    at Module.load (internal/modules/cjs/loader.js:812:32)\n' +
                '    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n' +
                '    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)\n' +
                '    at internal/main/run_main_module.js:17:11\n'
            }
            {
              type: 'log',
              text: 'Bail out! Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.\n'
            }
    ...
not ok 2 SL_EDGE - [undefined ms] - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Stderr: 
             Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.
                at launch (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/launch.js:21:28)
                at main (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/index.js:7:10)
                at Object.<anonymous> (/Users/villander/Projects/ember-asset-loader/node_modules/ember-cli-sauce/bin/cli.js:6:1)
                at Module._compile (internal/modules/cjs/loader.js:956:30)
                at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
                at Module.load (internal/modules/cjs/loader.js:812:32)
                at Function.Module._load (internal/modules/cjs/loader.js:724:14)
                at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
                at internal/main/run_main_module.js:17:11
            
            Stdout: 
             Bail out! Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.
            
            
        Log: |
            { type: 'error', text: 'Error: Browser exited unexpectedly' }
            {
              type: 'error',
              text: 'Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.\n' +
                '    at launch (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/launch.js:21:28)\n' +
                '    at main (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/index.js:7:10)\n' +
                '    at Object.<anonymous> (/Users/villander/Projects/ember-asset-loader/node_modules/ember-cli-sauce/bin/cli.js:6:1)\n' +
                '    at Module._compile (internal/modules/cjs/loader.js:956:30)\n' +
                '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n' +
                '    at Module.load (internal/modules/cjs/loader.js:812:32)\n' +
                '    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n' +
                '    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)\n' +
                '    at internal/main/run_main_module.js:17:11\n'
            }
            {
              type: 'log',
              text: 'Bail out! Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.\n'
            }
    ...
not ok 3 SL_IE10 - [undefined ms] - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Stderr: 
             Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.
                at launch (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/launch.js:21:28)
                at main (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/index.js:7:10)
                at Object.<anonymous> (/Users/villander/Projects/ember-asset-loader/node_modules/ember-cli-sauce/bin/cli.js:6:1)
                at Module._compile (internal/modules/cjs/loader.js:956:30)
                at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
                at Module.load (internal/modules/cjs/loader.js:812:32)
                at Function.Module._load (internal/modules/cjs/loader.js:724:14)
                at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
                at internal/main/run_main_module.js:17:11
            
            Stdout: 
             Bail out! Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.
            
            
        Log: |
            { type: 'error', text: 'Error: Browser exited unexpectedly' }
            {
              type: 'error',
              text: 'Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.\n' +
                '    at launch (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/launch.js:21:28)\n' +
                '    at main (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/index.js:7:10)\n' +
                '    at Object.<anonymous> (/Users/villander/Projects/ember-asset-loader/node_modules/ember-cli-sauce/bin/cli.js:6:1)\n' +
                '    at Module._compile (internal/modules/cjs/loader.js:956:30)\n' +
                '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n' +
                '    at Module.load (internal/modules/cjs/loader.js:812:32)\n' +
                '    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n' +
                '    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)\n' +
                '    at internal/main/run_main_module.js:17:11\n'
            }
            {
              type: 'log',
              text: 'Bail out! Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.\n'
            }
    ...
not ok 4 SL_IE11 - [undefined ms] - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Stderr: 
             Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.
                at launch (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/launch.js:21:28)
                at main (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/index.js:7:10)
                at Object.<anonymous> (/Users/villander/Projects/ember-asset-loader/node_modules/ember-cli-sauce/bin/cli.js:6:1)
                at Module._compile (internal/modules/cjs/loader.js:956:30)
                at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
                at Module.load (internal/modules/cjs/loader.js:812:32)
                at Function.Module._load (internal/modules/cjs/loader.js:724:14)
                at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
                at internal/main/run_main_module.js:17:11
            
            Stdout: 
             Bail out! Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.
            
            
        Log: |
            { type: 'error', text: 'Error: Browser exited unexpectedly' }
            {
              type: 'error',
              text: 'Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.\n' +
                '    at launch (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/launch.js:21:28)\n' +
                '    at main (/Users/villander/Projects/ember-asset-loader/node_modules/saucie/lib/index.js:7:10)\n' +
                '    at Object.<anonymous> (/Users/villander/Projects/ember-asset-loader/node_modules/ember-cli-sauce/bin/cli.js:6:1)\n' +
                '    at Module._compile (internal/modules/cjs/loader.js:956:30)\n' +
                '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n' +
                '    at Module.load (internal/modules/cjs/loader.js:812:32)\n' +
                '    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n' +
                '    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)\n' +
                '    at internal/main/run_main_module.js:17:11\n'
            }
            {
              type: 'log',
              text: 'Bail out! Error: Please, provide the username and the access key for SauceLabs. Use the option --help for more information.\n'
            }
    ...

1..4
# tests 4
# pass  0
# skip  0
# fail  4
Testem finished with non-zero exit code. Tests failed.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  ember-asset-loader git:(master) 
```

**Comment by villander** [comment]
cc: @rwjblue

**Comment by SergeAstapov** [comment]
this was fixed by https://github.com/ember-engines/ember-asset-loader/pull/128
